import React from 'react';
import './FAQ.css';

const FAQ = () => {
  const faqs = [
    {
      question: "What is a trade signal?",
      answer: "A trade signal is a suggestion or recommendation for entering a trade on a financial instrument, typically at a specific price and time. These signals can be generated by human analysts or automated systems."
    },
    {
      question: "How are the trade signals delivered?",
      answer: "Trade signals are delivered in real-time to your dashboard on our platform. You will see the latest signals as soon as they are posted."
    },
    {
        question: "What kind of assets do you provide signals for?",
        answer: "We provide signals for a wide range of assets, including stocks, forex, commodities, and cryptocurrencies. The specific assets covered may vary depending on market conditions and our analysts' focus."
    },
    {
        question: "Are your trade signals guaranteed to be profitable?",
        answer: "No, trading in financial markets always involves risk, and past performance is not indicative of future results. Our signals are based on careful analysis, but we cannot guarantee profitability. We encourage you to use proper risk management techniques."
    },
    {
        question: "How often are new signals posted?",
        answer: "The frequency of new signals depends on market conditions. Our analysts are constantly monitoring the markets for opportunities, and we post new signals as soon as they are identified."
    },
    {
      question: "How can I contact you for support or more information?",
      answer: "For any questions or support, please feel free to email us at support@tradesignals.com. For business inquiries, please contact us at business@tradesignals.com. We're here to help you get started!"
    }
  ];

  return (
    <div className="faq-page">
      <div className="bento-box">
        <h2>Frequently Asked Questions</h2>
        <div className="faq-list">
          {faqs.map((faq, index) => (
            <div key={index} className="faq-item">
              <h3>{faq.question}</h3>
              <p>{faq.answer}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default FAQ;
